### ISSUE TITLE
Bug in game "uberswap"

### ISSUE THREAD

**Issue by No1Leader** [EgonOlsen71/uberswap#1]
Hi EgonOlson71,

thank you making this game. It's fun to play, but I found a small bug in it.
If you have two empty columns on the right side, select the item in the last row / last column and move the cursor to the right and push the fire button, then it moves the item to the right. If you do this again, the program reorganize the items and you get 2,000 extra points.

![uberswap](https://user-images.githubusercontent.com/85347784/120798089-24711600-c53d-11eb-9ff3-9efb148890c6.GIF)

**Comment by EgonOlsen71** [comment]
Interesting. Looks like as if it's always possible to move the cursor to the right into the empty column when actually, it shouldn't be. I'll have a look when I find the time.

**Comment by EgonOlsen71** [comment]
I think I've fixed it. Can you please give it a try and report back?

**Comment by No1Leader** [comment]
I download the new version and tested it. Now it works fine. Thank you for the fast fix.
